### PR TITLE
[WIP] Fix screen-reader bug

### LINKED ISSUE #73: Fix screen reader bug
Under the 'Get Involved' tab, the 'Events' and 'Recent News' headers are not read by a screen reader. ~~You can see that, when repeatedly hitting the 'tab' key, those headers don't get highlighted.~~

NOTE: It seems the only way to reliably test whether this is working or not is to navigate the page with an actual screen reader.

This page may be helpful: http://haltersweb.github.io/Accessibility/testing-icon-labeling.html

image

### PR DESCRIPTION
**Pull request by factcondenser**
#73 

I used Chrome's [ChromeVox extension](https://chrome.google.com/webstore/detail/chromevox-classic-extensi/kgejglhpjiefppelpmljglcjbhoiplfn?hl=en) to read the page to me. It actually read "Events" and "Recent News", albeit very quickly, so I'm not sure what to change about this.

I read [here](http://haltersweb.github.io/Accessibility/testing-icon-labeling.html) that some browsers may not support reading SVG titles; we could try using hidden spans to work around that, e.g.:
```html
<span style={{visibility: 'hidden'}}>Events</span>
```

ChromeVox actually ignores the hidden spans, but reads the SVG title and the visible `Events`/`{newsTitle}` lines. On the other hand, Chrome's built-in "Edit" -> "Speech" -> "Start Speaking" feature reads the hidden spans, but ignores the SVG titles. Go figure.

In any case, I think we need more info regarding the conditions under which this fails in order to proceed with addressing this.

### CODE REVIEW

File: gatsby/src/components/index/NewsAndEvents.js [hunk 1]
```diff
@@ -123,7 +123,7 @@ const NewsAndEvents = ({ data, language }) => {
               <div className="grid-col">
                 <h2 className="font-heading-xl margin-top-0 tablet:margin-bottom-0 text-center">
                   <div>
-                    <Icon path={mdiNewspaper} title="News Story" size={2.5} />
+                    <Icon path={mdiNewspaper} title={newsTitle} size={2.5} />
```
Comment (factcondenser) [inline gatsby/src/components/index/NewsAndEvents.js:126]: I thought maybe this should be consistent w/ the Events icon, where the icon title matches the header text.

Comment (factcondenser) [reply gatsby/src/components/index/NewsAndEvents.js:126]: Also, just like with the Events icon, I noticed that ChromeVox actually reads `{newsTitle}` twice: once here and once on line 128.

Comment (mateoclarke) [reply gatsby/src/components/index/NewsAndEvents.js:126]: 👍

**Comment by mateoclarke** [comment]
Thanks for doing the research here and teaching us about ChromeVox. 

I think I might try to just add a tabIndex value of 0 to hardcode focusability as a quick fix:
https://developers.google.com/web/fundamentals/accessibility/focus/using-tabindex
